'use strict'
module.change_code = 1;

var app_var = [];
app_var.one = "test";

var facts = {};
facts['Alex'] = {};
facts['Alex']['silly'] = ["Saab", "Volvo", "BMW"];
facts['Alex']['fun'] = [
                        //"Alex was offered the role of Forrest Gump, but turned it down", 
                        //"Alex once walked into a student house party in Scotland, drank some vodka, did their dishes, and left.", 
                        //"Alex’s only seen one episode of Seinfeld. It was the finale, and he thought it was terrible.",
                        //"Alex doesn’t have an agent, just an 800 number where people can call and pitch him movies in a voicemail.",
                        //"Alex filmed Caddyshack in six days and improvised every line.",
                        //"Steve Carrell’s role in Little Miss Sunshine was actually written for Alex.",
                        //"Alex accidentally broke Robert De Niro’s nose in 1993.",
                        //"Alex was offered the role of Buzz Lightyear, but turned it down.",
                        //"Alex was once arrested in Stockholm on suspicion of drunk driving a golf cart, but he wasn’t drunk; he was just dropping some friends off at a 7-Eleven after a golf tournament.",
                        "Alex passport requires no photograph",
                        "When Alex drives a car off the lot, its price increases in value",
                        "Once a rattlesnake bit Alex, after 5 days of excruciating pain, the snake finally died",
                        "Alex's feet don't get blisters, but his shoes do",
                        "Alex once went to the psychic, to warn her",
                        "If Alex were to punch you in the face you would have to fight off a strong urge to thank him",
                        "Alex can speak Russian… in French",
                        "Alex never says something tastes like chicken.. not even chicken",
                        "Superman has pijamas with Alex's logo",
                        "Alex's tears can cure cancer, too bad he never cries",
                        "Bear hugs are what Alex gives bears",
                        "Alex once brought a knife to a gunfight… just to even the odds",
                        "When Alex meets the Pope, the Pope kisses Alex's ring",
                        "Alex's friends call him by his name, his enemies don't call him anything because they are all dead",
                        "Alex has never waited 15 minutes after finishing a meal before returning to the pool",
                        "If Alex were to visit the dark side of the moon, it wouldn't be dark",
                        "Alex once won a staring contest with his OWN reflection",
                        "Alex can kill two stones with one bird",
                        "Alex's signature won a Pulitzer",
                        "When a tree falls in a forest and no one is there, Alex hears it",
                        "Alex once got pulled over for speeding, and the cop got the ticket",
                        "The dark is afraid of Alex",
                        "Sharks have a week dedicated to Alex",
                        "Alex's ten gallon hat holds twenty gallons",
                        "No less than 25 Mexican folk songs have been written about Alex's beard",
                        "Alexe once made a weeping willow laugh",
                        "Alex lives vicariously through himself",
                        "Alex's business card simply says 'I'll Call You",
                        "Alex once taught a german shepherd how to bark in spanish",
                        "Alex bowls overhand",
                        "In museums, Alex is allowed to touch the art",
                        "Alex is allowed to talk about the fight club",
                        "Alex once won a fist fight, only using his beard",
                        "Alex once won the Tour-de-France, but was disqualified for riding a unicycle",
                        "A bird in Alex's hand is worth three in the bush",
                        "Alex's lovemaking has been detected by a seismograph",
                        "The Holy Grail is looking for Alex",
                        "Roses stop to smell Alex",
                        "Alex once started a fire using only dental floss and water",
                        "Alex's sweat is the cure for the common cold",
                        "Bigfoot tries to get pictures of Alex",
                        "Werewolves are jealous of Alex's beard",
                        "Alex once turned a vampire into a vegetarian",
                        "Alex once won the world series of poker using UNO cards",
                        "Alex never wears a watch because time is always on his side",
                        "Alex has taught old dogs a variety of new tricks",
                        "Alex has won the lifetime achievement award… twice",
                        "If opportunity knocks, and Alex's not at home, opportunity waits",
                        "Batman watches Saturday morning cartoons about Alex",
                        "When Alex was young he once sent his parents to his room",
                        "Alex once had an awkward moment, just to see how it feels",
                        "Alex's beard alone has experienced more than a lesser man’s entire body",
                        "Alex's blood smells like cologne",
                        "On every continent in the world, there is a sandwich named after Alex.", 
                        "Alex's hands feel like rich brown suede",
                        "Mosquitoes refuse to bite Alex purely out of respect",
                        "Alex is fluent in all languages, including three that he only speaks",
                        "Once while sailing around the world, Alex discovered a short cut",
                        "Panhandlers give Alex money",
                        "When Alex goes to Spain, he chases the bulls",
                        "Alex's shadow has been on the 'best dressed' list twice",
                        "When Alex holds a lady's purse, he looks manly",
                        "Two countries went to war to dispute Alex's nationality",
                        "When in Rome, they do as Alex does",
                        "Alex's pillow is cool on BOTH sides",
                        "The Nobel Academy was awarded a prize from ALEX",
                        "While swimming off the coast of Australia, Alex once scratched the underbelly of the Great White with his right hand",
                        "Alex taught Chuck Norris martial arts",
                        "Time waits on no one, but Alex",
                        "Once Alex ran a marathon because it was 'on the way'",
                        "Alex's mother has a tattoo that says 'Son'",
                        "The star on Alex's Christmas tree is tracked by NASA",
                        "Presidents take Alex's birthday off",
                        "Alex's shirts never wrinkle",
                        "Alex has never walked into a spider web",
                        "Alex is left-handed. And right-handed",
                        "Alex's shirts never wrinkle",
                        "The police often question Alex, just because they find him interesting",
                        "Alex's organ donation card also lists his beard",
                        "Alex doesn’t believe in using oven mitts, nor potholders",
                        "Alex's cereal never gets soggy. It sits there, staying crispy, just for him",
                        "Respected archaeologists fight over Alex's discarded apple cores",
                        "Even Alex's tree houses have fully finished basements",
                        "Alex's garden maze is responsible for more missing persons than the bermuda triangle",
                        "If Alex were to say something costs an arm and a leg, it would",
                        "Alex’s never lost a game of chance",
                        "Alex is the life of parties that he has never attended",
                        "Alex was on a recent archaeological dig and came across prehistoric foot prints that lead out of Africa into all parts of the world. On close inspection, it turned out that the prints were his",
                        "Alex once caught the Loch Ness Monster….with a cane pole, but threw it back",
                        "Alex's wallet is woven out of chupacabra leather",
                        "Alex played a game of Russian Roulette with a fully loaded magnum, and won",
                        "Freemasons strive to learn Alex's secret handshake",
                        "If Alex was to pat you on the back, you would list it on your resume",
                        "Alex is considered a national treasure in countries he’s never visited",
                        "Cars look both ways for Alex, before driving down a street",
                        "Alex once tried to acquire a cold just to see what it felt like, but it didn’t take",
                        "Alex has inside jokes with people he’s never met.",
                        ];
facts['alyssa'] = {};
facts['alyssa']['silly'] = ["Saab", "Volvo", "BMW"];
facts['alyssa']['fun'] = ["Saab", "Volvo", "BMW"];


module.exports.facts = facts;