'use strict'
module.change_code = 1;

var app_var = [];
app_var.one = "test";

var facts = [
             "NAME passport requires no photograph.",
             "When NAME drives a car off the lot, its price increases in value.",
             "Once a rattlesnake bit NAME, after 5 days of excruciating pain, the snake finally died.",
             "NAME's feet don't get blisters, but his shoes do.",
             "NAME once went to the psychic, to warn her.",
             "If NAME were to punch you in the face you would have to fight off a strong urge to thank him.",
             "NAME can speak Russian. In French.",
             "NAME never says something tastes like chicken. Not even chicken.",
             "Superman has pijamas with NAME's logo.",
             "NAME's tears can cure cancer, too bad he never cries.",
             "Bear hugs are what NAME gives bears.",
             "NAME once brought a knife to a gunfight… just to even the odds.",
             "When NAME meets the Pope, the Pope kisses NAME's ring.",
             "NAME's friends call him by his name, his enemies don't call him anything because they are all dead.",
             "NAME has never waited 15 minutes after finishing a meal before returning to the pool.",
             "If NAME were to visit the dark side of the moon, it wouldn't be dark.",
             "NAME once won a staring contest with his OWN reflection.",
             "NAME can kill two stones with one bird.",
             "NAME's signature won a Pulitzer.",
             "When a tree falls in a forest and no one is there, NAME hears it.",
             "NAME once got pulled over for speeding, and the cop got the ticket.",
             "The dark is afraid of NAME.",
             "Sharks have a week dedicated to NAME.",
             "NAME's ten gallon hat holds twenty gallons.",
             "No less than 25 Mexican folk songs have been written about NAME's beard.",
             "NAME once made a weeping willow laugh.",
             "NAME lives vicariously through himself.",
             "NAME's business card simply says 'I'll Call You.",
             "NAME once taught a german shepherd how to bark in spanish.",
             "NAME bowls overhand.",
             "In museums, NAME is allowed to touch the art.",
             "NAME is allowed to talk about the fight club.",
             "NAME once won a fist fight, only using his beard.",
             "NAME once won the Tour-de-France, but was disqualified for riding a unicycle.",
             "A bird in NAME's hand is worth three in the bush.",
             "NAME's lovemaking has been detected by a seismograph.",
             "The Holy Grail is looking for NAME.",
             "Roses stop to smell NAME.",
             "NAME once started a fire using only dental floss and water.",
             "NAME's sweat is the cure for the common cold.",
             "Bigfoot tries to get pictures of NAME.",
             "Werewolves are jealous of NAME's beard.",
             "NAME once turned a vampire into a vegetarian.",
             "NAME once won the world series of poker using UNO cards.",
             "NAME never wears a watch because time is always on his side.",
             "NAME has taught old dogs a variety of new tricks.",
             "NAME has won the lifetime achievement award… twice.",
             "If opportunity knocks, and NAME's not at home, opportunity waits.",
             "Batman watches Saturday morning cartoons about NAME.",
             "When NAME was young he once sent his parents to his room.",
             "NAME once had an awkward moment, just to see how it feels.",
             "NAME's beard alone has experienced more than a lesser man’s entire body.",
             "NAME's blood smells like cologne.",
             "On every continent in the world, there is a sandwich named after NAME.", 
             "NAME's hands feel like rich brown suede.",
             "Mosquitoes refuse to bite NAME purely out of respect.",
             "NAME is fluent in all languages, including three that he only speaks.",
             "Once while sailing around the world, NAME discovered a short cut.",
             "Panhandlers give NAME money.",
             "When NAME goes to Spain, he chases the bulls.",
             "NAME's shadow has been on the 'best dressed' list twice.",
             "When NAME holds a lady's purse, he looks manly.",
             "Two countries went to war to dispute NAME's nationality.",
             "When in Rome, they do as NAME does.",
             "NAME's pillow is cool on BOTH sides.",
             "The Nobel Academy was awarded a prize from NAME.",
             "While swimming off the coast of Australia, NAME once scratched the underbelly of the Great White with his right hand.",
             "NAME taught Chuck Norris martial arts.",
             "Time waits on no one, but NAME.",
             "Once NAME ran a marathon because it was 'on the way'.",
             "NAME's mother has a tattoo that says 'Son'.",
             "The star on NAME's Christmas tree is tracked by NASA.",
             "Presidents take NAME's birthday off.",
             "NAME's shirts never wrinkle.",
             "NAME has never walked into a spider web.",
             "NAME is left-handed. And right-handed.",
             "NAME's shirts never wrinkle.",
             "The police often question NAME, just because they find him interesting.",
             "NAME's organ donation card also lists his beard.",
             "NAME doesn’t believe in using oven mitts, nor potholders.",
             "NAME's cereal never gets soggy. It sits there, staying crispy, just for him.",
             "Respected archaeologists fight over NAME's discarded apple cores.",
             "Even NAME's tree houses have fully finished basements.",
             "NAME's garden maze is responsible for more missing persons than the bermuda triangle.",
             "If NAME were to say something costs an arm and a leg, it would.",
             "NAME’s never lost a game of chance.",
             "NAME is the life of parties that he has never attended.",
             "NAME was on a recent archaeological dig and came across prehistoric foot prints that lead out of Africa into all parts of the world. On close inspection, it turned out that the prints were his.",
             "NAME once caught the Loch Ness Monster….with a cane pole, but threw it back.",
             "NAME's wallet is woven out of chupacabra leather.",
             "NAME played a game of Russian Roulette with a fully loaded magnum, and won.",
             "Freemasons strive to learn NAME's secret handshake.",
             "If NAME was to pat you on the back, you would list it on your resume.",
             "NAME is considered a national treasure in countries he’s never visited.",
             "Cars look both ways for NAME, before driving down a street.",
             "NAME once tried to acquire a cold just to see what it felt like, but it didn’t take.",
             "NAME has inside jokes with people he’s never met.",
             ];
var reprompt_msg = [
    "Do you want to hear more?",
    "want another one?",
    "I can tell you another one if you want?",
    "Should I continue?" 
];

module.exports.reprompt_msg = reprompt_msg;
module.exports.facts = facts;